(()=>{
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const STORE='itinerarioArtistico.projects.v4';
const demo={title:'Lecce barocca · itinerario guida',desc:'Tre tappe nel cuore del barocco leccese.',city:{name:'Lecce',display_name:'Lecce, Puglia, Italia',lat:40.3515,lon:18.175},stops:[
{title:'Basilica di Santa Croce',subtitle:'Barocco leccese',date:'XVI–XVII secolo',place:'Via Umberto I, Lecce',lat:40.35404,lon:18.17202,desc:'La facciata di Santa Croce è uno dei massimi esempi del barocco leccese.',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Basilica_di_Santa_Croce_%28Lecce%29.jpg/500px-Basilica_di_Santa_Croce_%28Lecce%29.jpg',credit:'Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Basilica_di_Santa_Croce_(Lecce).jpg'},
{title:'Chiesa di Sant’Irene',subtitle:'Barocco leccese',date:'XVII secolo',place:'Lecce',lat:40.35283,lon:18.17109,desc:'La chiesa di Sant’Irene presenta una facciata monumentale e un interno ricco di altari barocchi.',image:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg/960px-Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg",credit:'Wikimedia Commons',source:"https://commons.wikimedia.org/wiki/File:Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg"},
{title:'Piazza Duomo',subtitle:'Complesso episcopale',date:'XVII secolo',place:'Piazza del Duomo, Lecce',lat:40.35212,lon:18.16867,desc:'Piazza Duomo è uno degli spazi scenografici più importanti della città.',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Piazza_duomo_Lecce.jpg/1280px-Piazza_duomo_Lecce.jpg',credit:'Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Piazza_duomo_Lecce.jpg'}]};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let projects=[]; try{projects=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{}; if(!projects.length){projects=[{id:uid(),created:Date.now(),updated:Date.now(),...demo}];saveAll()}
let activeId=null,current=0,map,markers=[],routeLayers=[],routeLabels=[],segments=[],clickAdd=false,deferredPrompt;
function saveAll(){localStorage.setItem(STORE,JSON.stringify(projects))} function active(){return projects.find(p=>p.id===activeId)} function stops(){return active()?.stops||[]} function save(){if(active()){active().updated=Date.now();saveAll()}}
function openModal(html){$('modal').innerHTML=html;$('modalBack').classList.remove('hidden')} function closeModal(){$('modalBack').classList.add('hidden');$('modal').innerHTML=''} $('modalBack').onclick=e=>{if(e.target===$('modalBack'))closeModal()};
function renderLibrary(){activeId=null;$('library').classList.remove('hidden');$('app').classList.add('hidden');document.body.classList.remove('presentation');$('library').innerHTML='<div class="libraryInner"><div class="libraryTop"><small>Itinerario Artistico</small><h1>I miei itinerari</h1><p>Crea, modifica e presenta percorsi artistici sul territorio.</p></div><div class="projectGrid" id="grid"></div></div>';const g=$('grid');projects.forEach(p=>{const cover=p.stops.find(s=>s.image)?.image||'';const c=document.createElement('article');c.className='projectCard';c.innerHTML=`<div class="cover">${cover?`<img src="${esc(cover)}">`:''}<span class="count">${p.stops.length} tappe</span></div><div class="cardBody"><h3>${esc(p.title)}</h3><p>${esc(p.desc||'')}</p><div class="cardActions"><button class="btn primary" data-o>Apri</button><button class="btn" data-p>Presenta</button><button class="btn" data-d>Duplica</button><button class="btn" data-x>Elimina</button></div></div>`;c.querySelector('[data-o]').onclick=()=>openProject(p.id,false);c.querySelector('[data-p]').onclick=()=>openProject(p.id,true);c.querySelector('[data-d]').onclick=()=>{const n=JSON.parse(JSON.stringify(p));n.id=uid();n.title+=' · copia';projects.push(n);saveAll();renderLibrary()};c.querySelector('[data-x]').onclick=()=>{if(confirm('Eliminare questo itinerario?')){projects=projects.filter(x=>x.id!==p.id);if(!projects.length)projects=[{id:uid(),...demo}];saveAll();renderLibrary()}};g.appendChild(c)});const n=document.createElement('div');n.className='newCard';n.innerHTML='<button><b>＋</b><span>Nuovo itinerario</span></button>';n.onclick=newProject;g.appendChild(n)}
function newProject(){openModal('<h2>Nuovo itinerario</h2><div class="field"><label>Titolo</label><input id="nt" placeholder="Es. Lecce romana"></div><div class="field"><label>Descrizione</label><input id="nd"></div><div class="modalFoot"><button class="btn" id="nc">Annulla</button><button class="btn primary" id="nok">Crea</button></div>');$('nc').onclick=closeModal;$('nok').onclick=()=>{const p={id:uid(),title:$('nt').value.trim()||'Nuovo itinerario',desc:$('nd').value.trim(),created:Date.now(),updated:Date.now(),stops:[]};projects.push(p);saveAll();closeModal();openProject(p.id,false);setTimeout(openAdd,200)}}
function initMap(){if(map)return;map=L.map('map').setView([40.3515,18.175],15);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'}).addTo(map);map.on('click',e=>{if(!clickAdd)return;clickAdd=false;$('mapHint').innerHTML='Seleziona una tappa oppure premi <b>Avanti</b>.';addStop({title:'Nuova tappa',subtitle:'',date:'',place:'',lat:e.latlng.lat,lon:e.latlng.lng,desc:'',image:''});editCurrent()})}
function openProject(id,present){activeId=id;current=0;$('library').classList.add('hidden');$('app').classList.remove('hidden');$('projectName').textContent=active().title;initMap();setTimeout(()=>map.invalidateSize(),80);rebuildMarkers();renderSlide();calcRoute(true).then(()=>{fitAll();if(present)presentMode()})}
function fitAll(){const s=stops();if(!s.length)return;if(s.length===1)map.setView([s[0].lat,s[0].lon],17);else map.fitBounds(L.latLngBounds(s.map(x=>[x.lat,x.lon])),{padding:[30,30]})}
function icon(i){return L.divIcon({className:'',iconSize:[34,34],iconAnchor:[17,34],html:`<div class="markerPin ${i===current?'active':''}"><span>${i+1}</span></div>`})}
function rebuildMarkers(){markers.forEach(m=>m.remove());markers=[];stops().forEach((s,i)=>{const m=L.marker([s.lat,s.lon],{icon:icon(i)}).addTo(map);m.onclick=null;m.on('click',()=>{current=i;renderSlide();refreshMarkers();map.flyTo([s.lat,s.lon],Math.max(map.getZoom(),16),{duration:.5})});markers.push(m)})} function refreshMarkers(){markers.forEach((m,i)=>m.setIcon(icon(i)))}
function renderSlide(){const a=stops(),s=a[current];if(!s){$('slide').innerHTML='<div class="eyebrow">Nessuna tappa</div><h1>Inizia il tuo itinerario</h1><p class="desc">Premi “＋ Tappa”.</p>';$('progressBar').style.width='0';$('stepText').textContent='0 tappe';return}const img=s.image?`<img src="${esc(s.image)}" alt="">`:`<div class="placeholder"><div><strong>${esc(s.title)}</strong><br>Aggiungi un’immagine</div></div>`;const cr=s.credit?`<div class="credit">Foto: ${esc(s.credit)}${s.source?` · <a href="${esc(s.source)}" target="_blank">fonte</a>`:''}</div>`:'';$('slide').innerHTML=`<div class="eyebrow">Tappa ${current+1} di ${a.length}</div><h1>${esc(s.title)}</h1><div class="meta">${[s.subtitle,s.date,s.place].filter(Boolean).map(esc).join(' · ')}</div><div class="hero">${img}</div><div class="photoActions"><button class="btn" id="photoBtn">📷 ${s.image?'Cambia immagine':'Aggiungi immagine'}</button></div>${cr}<p class="desc">${esc(s.desc||'Aggiungi una breve descrizione.')}</p>`;$('photoBtn').onclick=()=>$('photoPicker').click();$('progressBar').style.width=((current+1)/a.length*100)+'%';$('stepText').textContent=`${current+1} / ${a.length}`;refreshMarkers();updateSummary()}
$('prevBtn').onclick=()=>{if(current>0){current--;renderSlide();focus()}};$('nextBtn').onclick=()=>{if(current<stops().length-1){current++;renderSlide();focus()}};function focus(){const s=stops()[current];if(s)map.flyTo([s.lat,s.lon],Math.max(16,map.getZoom()),{duration:.5})}
$('homeBtn').onclick=renderLibrary;$('backBtn').onclick=()=>{if(document.body.classList.contains('presentation')){document.body.classList.remove('presentation');setTimeout(()=>map.invalidateSize(),80)}else renderLibrary()};$('showAllBtn').onclick=fitAll;$('presentBtn').onclick=presentMode;function presentMode(){document.body.classList.add('presentation');setTimeout(()=>map.invalidateSize(),80);fitAll()}
$('photoPicker').onchange=async e=>{const f=e.target.files[0],s=stops()[current];if(!f||!s)return;const r=new FileReader();r.onload=()=>{s.image=r.result;s.credit='';s.source='';save();renderSlide()};r.readAsDataURL(f);e.target.value=''};
function addStop(s){active().stops.push(s);current=stops().length-1;save();rebuildMarkers();renderSlide();calcRoute(true);focus()}
$('addStopBtn').onclick=openAdd;function openAdd(){const c=active().city;openModal(`<h2>Aggiungi tappa</h2><div id="cityBox">${c?cityChosen(c):citySearch()}</div><div id="poiBox" class="${c?'':'hidden'}">${poiSearch()}</div><div class="modalFoot"><button class="btn" id="mapPick">📍 Punto sulla mappa</button><button class="btn" id="closeAdd">Chiudi</button></div>`);wireAdd();$('mapPick').onclick=()=>{closeModal();clickAdd=true;$('mapHint').innerHTML='<b>Clicca sulla mappa</b> nel punto della nuova tappa.'};$('closeAdd').onclick=closeModal}
function citySearch(){return '<div class="field"><label>Cerca città</label><div class="row"><input id="cq"><button class="btn primary" id="cs">Cerca</button></div></div><div id="cr" class="resultList"></div>'} function cityChosen(c){return `<div class="note"><b>${esc(c.name)}</b><br>${esc(c.display_name||'')} <button class="btn" id="changeCity">Cambia</button></div>`} function poiSearch(){return '<div class="field"><label>Punto d’interesse</label><div class="row"><input id="pq"><button class="btn primary" id="ps">Cerca</button></div></div><div class="chips"><button class="chip" data-q="museo">Musei</button><button class="chip" data-q="chiesa">Chiese</button><button class="chip" data-q="monumento">Monumenti</button><button class="chip" data-q="piazza">Piazze</button></div><div id="pr" class="resultList"></div>'}
function wireAdd(){if($('changeCity'))$('changeCity').onclick=()=>{$('cityBox').innerHTML=citySearch();$('poiBox').classList.add('hidden');wireAdd()};if($('cs')){$('cs').onclick=findCity;$('cq').onkeydown=e=>{if(e.key==='Enter')findCity()}}if($('ps')){$('ps').onclick=findPoi;$('pq').onkeydown=e=>{if(e.key==='Enter')findPoi()};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('pq').value=b.dataset.q;findPoi()})}}
async function nom(q,extra={}){const u=new URL('https://nominatim.openstreetmap.org/search');Object.entries({format:'jsonv2',addressdetails:'1',limit:'8',q,...extra}).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw 0;return r.json()}
async function findCity(){const q=$('cq').value.trim();if(q.length<2)return;$('cr').innerHTML='<div class="note">Ricerca…</div>';try{const d=await nom(q,{featuretype:'city'});$('cr').innerHTML='';d.forEach(x=>{const b=document.createElement('button');b.className='result';b.innerHTML=`<b>${esc(x.name||x.display_name.split(',')[0])}</b><small>${esc(x.display_name)}</small>`;b.onclick=()=>{active().city={name:x.name||x.display_name.split(',')[0],display_name:x.display_name,lat:+x.lat,lon:+x.lon,country_code:x.address?.country_code||''};save();$('cityBox').innerHTML=cityChosen(active().city);$('poiBox').classList.remove('hidden');wireAdd();map.setView([+x.lat,+x.lon],13)};$('cr').appendChild(b)})}catch{$('cr').innerHTML='<div class="note">Ricerca non disponibile.</div>'}}
async function findPoi(){const c=active().city,q=$('pq').value.trim();if(!c||q.length<2)return;$('pr').innerHTML='<div class="note">Ricerca…</div>';try{let d=await nom(q+', '+c.name,c.country_code?{countrycodes:c.country_code}:{});if(!d.length)d=await nom(q);$('pr').innerHTML='';d.forEach(x=>{const t=x.name||x.display_name.split(',')[0],b=document.createElement('button');b.className='result';b.innerHTML=`<b>${esc(t)}</b><small>${esc(x.display_name)}</small>`;b.onclick=()=>{addStop({title:t,subtitle:'',date:'',place:x.display_name,lat:+x.lat,lon:+x.lon,desc:'',image:''});closeModal()};$('pr').appendChild(b)})}catch{$('pr').innerHTML='<div class="note">Servizio momentaneamente non disponibile.</div>'}}
$('editStopBtn').onclick=editCurrent;function editCurrent(){const s=stops()[current];if(!s)return;openModal(`<h2>Modifica tappa ${current+1}</h2><div class="field"><label>Titolo</label><input id="et" value="${esc(s.title)}"></div><div class="row"><div class="field"><label>Autore / tema</label><input id="es" value="${esc(s.subtitle||'')}"></div><div class="field"><label>Data</label><input id="ed" value="${esc(s.date||'')}"></div></div><div class="field"><label>Luogo</label><input id="ep" value="${esc(s.place||'')}"></div><div class="field"><label>Descrizione</label><textarea id="ee">${esc(s.desc||'')}</textarea></div><div class="modalFoot"><button class="btn red" id="del">Elimina</button><button class="btn" id="ec">Annulla</button><button class="btn primary" id="eok">Salva</button></div>`);$('ec').onclick=closeModal;$('eok').onclick=()=>{s.title=$('et').value.trim()||'Tappa';s.subtitle=$('es').value.trim();s.date=$('ed').value.trim();s.place=$('ep').value.trim();s.desc=$('ee').value.trim();save();closeModal();rebuildMarkers();renderSlide()};$('del').onclick=()=>{if(confirm('Eliminare questa tappa?')){active().stops.splice(current,1);current=Math.max(0,Math.min(current,stops().length-1));save();closeModal();rebuildMarkers();renderSlide();calcRoute(true)}}}
$('settingsBtn').onclick=()=>openModal(`<h2>Impostazioni</h2><div class="field"><label>Titolo</label><input id="pt" value="${esc(active().title)}"></div><div class="field"><label>Descrizione</label><input id="pd" value="${esc(active().desc||'')}"></div><div class="note">Gli itinerari restano nel browser del dispositivo. Esporta/Importa per trasferirli.</div><div class="modalFoot"><button class="btn" id="imp">Importa</button><button class="btn" id="exp">Esporta</button><button class="btn" id="sc">Annulla</button><button class="btn primary" id="sok">Salva</button></div>`);
document.addEventListener('click',e=>{if(e.target.id==='sc')closeModal();if(e.target.id==='sok'){active().title=$('pt').value.trim()||active().title;active().desc=$('pd').value.trim();save();$('projectName').textContent=active().title;closeModal()}if(e.target.id==='exp'){const b=new Blob([JSON.stringify({project:active()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='itinerario.json';a.click()}if(e.target.id==='imp')$('importPicker').click()});
$('importPicker').onchange=async e=>{try{const o=JSON.parse(await e.target.files[0].text()),p=o.project||o;if(!Array.isArray(p.stops))throw 0;p.id=uid();p.title=(p.title||'Itinerario')+' · importato';projects.push(p);saveAll();closeModal();openProject(p.id,false)}catch{alert('File non valido.')}e.target.value=''};
function clearRoute(){routeLayers.forEach(x=>x.remove());routeLabels.forEach(x=>x.remove());routeLayers=[];routeLabels=[];segments=[]}
async function calcRoute(fit){clearRoute();const s=stops();if(s.length<2){updateSummary();return}for(let i=0;i<s.length-1;i++){let seg;try{seg=await ped(s[i],s[i+1])}catch{seg=fallback(s[i],s[i+1])}segments.push(seg);routeLayers.push(L.polyline(seg.points,{color:seg.real?'#b42318':'#777',weight:5,dashArray:seg.real?null:'8 7'}).addTo(map));const mid=seg.points[Math.floor(seg.points.length/2)];routeLabels.push(L.marker(mid,{interactive:false,icon:L.divIcon({className:'routeLabel',html:`${i+1}→${i+2} · ${fmtD(seg.distance)} · ${fmtT(seg.time)}`})}).addTo(map))}updateSummary();if(fit)fitAll()}
async function ped(a,b){const req={locations:[{lat:a.lat,lon:a.lon},{lat:b.lat,lon:b.lon}],costing:'pedestrian',units:'kilometers'};const r=await fetch('https://valhalla1.openstreetmap.de/route?json='+encodeURIComponent(JSON.stringify(req)));if(!r.ok)throw 0;const j=await r.json(),l=j.trip?.legs?.[0];if(!l?.shape)throw 0;return{real:true,points:decode(l.shape),distance:(l.summary.length||0)*1000,time:l.summary.time||0}}
function decode(str){let i=0,lat=0,lng=0,o=[];while(i<str.length){let b,s=0,r=0;do{b=str.charCodeAt(i++)-63;r|=(b&31)<<s;s+=5}while(b>=32);lat+=(r&1)?~(r>>1):(r>>1);s=0;r=0;do{b=str.charCodeAt(i++)-63;r|=(b&31)<<s;s+=5}while(b>=32);lng+=(r&1)?~(r>>1):(r>>1);o.push([lat/1e6,lng/1e6])}return o}
function hav(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,A=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))} function fallback(a,b){const d=hav(a.lat,a.lon,b.lat,b.lon);return{real:false,points:[[a.lat,a.lon],[b.lat,b.lon]],distance:d,time:d/5000*3600}} function fmtD(m){return m<1000?Math.round(m)+' m':(m/1000).toFixed(1).replace('.',',')+' km'} function fmtT(s){const m=Math.max(1,Math.round(s/60));return m<60?m+' min':Math.floor(m/60)+' h '+(m%60)+' min'}
function updateSummary(){const b=$('routeSummary');if(!segments.length){b.classList.add('hidden');return}const d=segments.reduce((a,x)=>a+x.distance,0),t=segments.reduce((a,x)=>a+x.time,0),i=Math.max(0,Math.min(current-1,segments.length-1)),s=segments[i];b.innerHTML=`<div><small>TRATTO ${i+1}→${i+2}</small><b>${fmtD(s.distance)} · ${fmtT(s.time)}</b></div><div class="sep"></div><div><small>TOTALE A PIEDI</small><b>${fmtD(d)} · ${fmtT(t)}</b></div>`;b.classList.remove('hidden')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;$('installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderLibrary();
})();