(()=>{
'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const STORE='itinerarioArtistico.projects.v4';
const demo={title:'Lecce barocca · itinerario guida',desc:'Tre tappe nel cuore del barocco leccese.',city:{name:'Lecce',display_name:'Lecce, Puglia, Italia',lat:40.3515,lon:18.175},stops:[
{title:'Basilica di Santa Croce',subtitle:'Barocco leccese',date:'XVI–XVII secolo',place:'Via Umberto I, Lecce',lat:40.35404,lon:18.17202,desc:'La facciata di Santa Croce è uno dei massimi esempi del barocco leccese.',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Basilica_di_Santa_Croce_%28Lecce%29.jpg/500px-Basilica_di_Santa_Croce_%28Lecce%29.jpg',credit:'Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Basilica_di_Santa_Croce_(Lecce).jpg'},
{title:'Chiesa di Sant’Irene',subtitle:'Barocco leccese',date:'XVII secolo',place:'Lecce',lat:40.35283,lon:18.17109,desc:'La chiesa di Sant’Irene presenta una facciata monumentale e un interno ricco di altari barocchi.',image:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg/960px-Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg",credit:'Wikimedia Commons',source:"https://commons.wikimedia.org/wiki/File:Lecce_Chiesa_di_Sant%27Irene_dei_Teatini.jpg"},
{title:'Piazza Duomo',subtitle:'Complesso episcopale',date:'XVII secolo',place:'Piazza del Duomo, Lecce',lat:40.35212,lon:18.16867,desc:'Piazza Duomo è uno degli spazi scenografici più importanti della città.',image:'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Piazza_duomo_Lecce.jpg/1280px-Piazza_duomo_Lecce.jpg',credit:'Wikimedia Commons',source:'https://commons.wikimedia.org/wiki/File:Piazza_duomo_Lecce.jpg'}]};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let projects=[]; try{projects=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{}; if(!projects.length){projects=[{id:uid(),created:Date.now(),updated:Date.now(),...demo}];saveProjects()}
let activeId=null,current=0,map,markers=[],routeLayers=[],routeLabels=[],segments=[],clickAdd=false,deferredPrompt;
function saveProjects(){localStorage.setItem(STORE,JSON.stringify(projects))} function active(){return projects.find(p=>p.id===activeId)} function stops(){return active()?.stops||[]}
function openModal(html){$('modal').innerHTML=html;$('modalBack').classList.remove('hidden')} function closeModal(){$('modalBack').classList.add('hidden');$('modal').innerHTML=''} $('modalBack').onclick=e=>{if(e.target===$('modalBack'))closeModal()};
function renderLibrary(){activeId=null;$('library').classList.remove('hidden');$('app').classList.add('hidden');document.body.classList.remove('presentation');$('library').innerHTML='<div class="libraryInner"><div class="libraryTop"><small>Itinerario Artistico</small><h1>I miei itinerari</h1><p>Crea, modifica e presenta percorsi artistici sul territorio.</p></div><div class="projectGrid" id="grid"></div></div>';const g=$('grid');projects.forEach(p=>{const cover=p.stops.find(s=>s.image)?.image||'';const c=document.createElement('article');c.className='projectCard';c.innerHTML=`<div class="cover">${cover?`<img src="${esc(cover)}">`:''}<span class="count">${p.stops.length} tappe</span></div><div class="cardBody"><h3>${esc(p.title)}</h3><p>${esc(p.desc||'')}</p><div class="cardActions"><button class="btn primary" data-o>Apri</button><button class="btn" data-p>Presenta</button><button class="btn" data-d>Duplica</button><button class="btn" data-x>Elimina</button></div></div>`;c.querySelector('[data-o]').onclick=()=>openProject(p.id,false);c.querySelector('[data-p]').onclick=()=>openProject(p.id,true);c.querySelector('[data-d]').onclick=()=>{const n=JSON.parse(JSON.stringify(p));n.id=uid();n.title+=' · copia';projects.push(n);saveProjects();renderLibrary()};c.querySelector('[data-x]').onclick=()=>{if(confirm('Eliminare questo itinerario?')){projects=projects.filter(x=>x.id!==p.id);if(!projects.length)projects=[{id:uid(),...demo}];saveProjects();renderLibrary()}};g.appendChild(c)});const n=document.createElement('div');n.className='newCard';n.innerHTML='<button><b>＋</b><span>Nuovo itinerario</span></button>';n.onclick=newProject;g.appendChild(n)}
function newProject(){openModal('<h2>Nuovo itinerario</h2><div class="field"><label>Titolo</label><input id="nt" placeholder="Es. Lecce romana"></div><div class="field"><label>Descrizione</label><input id="nd"></div><div class="modalFoot"><button class="btn" id="nc">Annulla</button><button class="btn primary" id="nok">Crea</button></div>');$('nc').onclick=closeModal;$('nok').onclick=()=>{const p={id:uid(),title:$('nt').value.trim()||'Nuovo itinerario',desc:$('nd').value.trim(),created:Date.now(),updated:Date.now(),stops:[]};projects.push(p);saveProjects();closeModal();openProject(p.id,false);setTimeout(openAddStop,200)}}
function initMap(){
  if(map)return;
  map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([40.3515,18.175],15);
  const providers=[
    {name:'Esri',url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',opts:{maxZoom:19,attribution:'Tiles &copy; Esri'}},
    {name:'CARTO',url:'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',opts:{subdomains:'abcd',maxZoom:20,attribution:'&copy; OpenStreetMap contributors &copy; CARTO'}},
    {name:'OSM HOT',url:'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',opts:{subdomains:'abc',maxZoom:20,attribution:'&copy; OpenStreetMap contributors, Tiles style by HOT'}}
  ];
  let baseLayer=null,providerIndex=0,errorCount=0,switching=false;
  function loadProvider(i){
    providerIndex=i%providers.length; errorCount=0; switching=false;
    if(baseLayer) map.removeLayer(baseLayer);
    const p=providers[providerIndex];
    baseLayer=L.tileLayer(p.url,{...p.opts,keepBuffer:3,updateWhenIdle:false,updateWhenZooming:false});
    baseLayer.on('tileload',()=>{errorCount=0});
    baseLayer.on('tileerror',()=>{
      errorCount++;
      if(errorCount>=3 && !switching && providerIndex<providers.length-1){
        switching=true;
        const next=providerIndex+1;
        setTimeout(()=>loadProvider(next),80);
      }
    });
    baseLayer.addTo(map);
  }
  loadProvider(0);
  map.whenReady(()=>setTimeout(()=>map.invalidateSize(true),120));
  window.addEventListener('resize',()=>setTimeout(()=>map.invalidateSize(true),120));
  map.on('click',e=>{if(!clickAdd)return;clickAdd=false;$('mapHint').innerHTML='Seleziona una tappa oppure premi <b>Avanti</b>.';addStop({title:'Nuova tappa',subtitle:'',date:'',place:'',lat:e.latlng.lat,lon:e.latlng.lng,desc:'',image:''});editCurrent()})
}
function openProject(id,present){activeId=id;current=0;$('library').classList.add('hidden');$('app').classList.remove('hidden');$('projectName').textContent=active().title;initMap();setTimeout(()=>map.invalidateSize(),80);rebuildMarkers();renderSlide();calculateRoute(true).then(()=>{fitProject();if(present)enterPresentation()})}
function fitProject(){const ss=stops();if(!ss.length)return;if(ss.length===1)map.setView([ss[0].lat,ss[0].lon],17);else map.fitBounds(L.latLngBounds(ss.map(x=>[x.lat,x.lon])),{padding:[30,30]})}
function markerIcon(i){return L.divIcon({className:'',iconSize:[34,34],iconAnchor:[17,34],html:`<div class="markerPin ${i===current?'active':''}"><span>${i+1}</span></div>`})}
function rebuildMarkers(){markers.forEach(m=>m.remove());markers=[];stops().forEach((s,i)=>{const m=L.marker([s.lat,s.lon],{icon:markerIcon(i)}).addTo(map);m.on('click',()=>{current=i;renderSlide();refreshMarkerIcons();map.flyTo([s.lat,s.lon],Math.max(map.getZoom(),16),{duration:.5})});markers.push(m)})} function refreshMarkerIcons(){markers.forEach((m,i)=>m.setIcon(markerIcon(i)))}
function renderSlide(){const ss=stops(),s=ss[current];if(!s){$('slide').innerHTML='<div class="eyebrow">Nessuna tappa</div><h1>Inizia il tuo itinerario</h1><p class="desc">Premi “＋ Tappa”.</p>';$('progressBar').style.width='0';$('stepText').textContent='0 tappe';return}const img=s.image?`<img src="${esc(s.image)}" alt="">`:`<div class="placeholder"><div><strong>${esc(s.title)}</strong><br>Aggiungi un’immagine</div></div>`;const cr=s.credit?`<div class="credit">Foto: ${esc(s.credit)}${s.source?` · <a href="${esc(s.source)}" target="_blank">fonte</a>`:''}</div>`:'';$('slide').innerHTML=`<div class="eyebrow">Tappa ${current+1} di ${ss.length}</div><h1>${esc(s.title)}</h1><div class="meta">${[s.subtitle,s.date,s.place].filter(Boolean).map(esc).join(' · ')}</div><div class="hero">${img}</div><div class="photoActions"><button class="btn" id="photoBtn">📷 ${s.image?'Cambia immagine':'Aggiungi immagine'}</button></div>${cr}<p class="desc">${esc(s.desc||'Aggiungi una breve descrizione.')}</p>`;
  $('photoBtn').onclick=()=>$('photoPicker').click();$('progressBar').style.width=((current+1)/ss.length*100)+'%';$('stepText').textContent=`${current+1} / ${ss.length}`;refreshMarkerIcons();updateRouteSummary()
}
function focusCurrent(){const s=stops()[current];if(s)map.flyTo([s.lat,s.lon],Math.max(map.getZoom(),16),{duration:.55})}
$('prevBtn').onclick=()=>{if(current>0){current--;renderSlide();focusCurrent()}};$('nextBtn').onclick=()=>{if(current<stops().length-1){current++;renderSlide();focusCurrent()}};
$('homeBtn').onclick=renderLibrary;$('backBtn').onclick=()=>{if(document.body.classList.contains('presentation')){document.body.classList.remove('presentation');setTimeout(()=>map.invalidateSize(),80)}else renderLibrary()};
$('showAllBtn').onclick=fitProject;$('presentBtn').onclick=enterPresentation;function enterPresentation(){document.body.classList.add('presentation');setTimeout(()=>map.invalidateSize(),80);fitProject()}
document.addEventListener('keydown',e=>{if(!document.body.classList.contains('presentation'))return;if(e.key==='Escape')document.body.classList.remove('presentation');if(e.key==='ArrowRight')$('nextBtn').click();if(e.key==='ArrowLeft')$('prevBtn').click()});

$('photoPicker').onchange=async e=>{const f=e.target.files[0];if(!f||!stops()[current])return;stops()[current].image=await fileData(f);stops()[current].credit='';stops()[current].source='';saveActive();renderSlide();e.target.value=''};function fileData(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function saveActive(){const p=active();if(p){p.updated=Date.now();saveProjects()}}
function addStop(s){active().stops.push(s);current=active().stops.length-1;saveActive();rebuildMarkers();renderSlide();calculateRoute(true);focusCurrent()}

$('addStopBtn').onclick=openAddStop;function openAddStop(){const city=active()?.city;openModal(`<h2>Aggiungi una tappa</h2><div id="cityBlock">${city?selectedCityHtml(city):citySearchHtml()}</div><div id="poiBlock" class="${city?'':'hidden'}">${poiHtml()}</div><div class="modalFoot"><button class="btn" id="mapPoint">📍 Punto sulla mappa</button><button class="btn" id="cancelAdd">Chiudi</button></div>`);wireCityPoi();$('mapPoint').onclick=()=>{closeModal();clickAdd=true;$('mapHint').innerHTML='<b>Clicca sulla mappa</b> nel punto della nuova tappa.'};$('cancelAdd').onclick=closeModal}
function citySearchHtml(){return `<div class="field"><label>Cerca città</label><div class="row"><input id="cityQuery" placeholder="Es. Lecce"><button class="btn primary" id="citySearch">Cerca</button></div></div><div id="cityResults" class="resultList"></div>`}
function selectedCityHtml(c){return `<div class="note"><b>${esc(c.name)}</b><br>${esc(c.display_name||'')} <button class="btn" id="changeCity" style="float:right;padding:5px 8px">Cambia</button></div>`}
function poiHtml(){return `<div class="field"><label>Punto d’interesse</label><div class="row"><input id="poiQuery" placeholder="Es. Santa Croce"><button class="btn primary" id="poiSearch">Cerca</button></div></div><div class="chips"><button class="chip" data-q="museo">Musei</button><button class="chip" data-q="chiesa">Chiese</button><button class="chip" data-q="monumento">Monumenti</button><button class="chip" data-q="piazza">Piazze</button><button class="chip" data-q="sito archeologico">Archeologia</button></div><div id="poiResults" class="resultList"></div>`}
function wireCityPoi(){const change=$('changeCity');if(change)change.onclick=()=>{$('cityBlock').innerHTML=citySearchHtml();$('poiBlock').classList.add('hidden');wireCityPoi()};const cs=$('citySearch');if(cs){cs.onclick=searchCity;$('cityQuery').onkeydown=e=>{if(e.key==='Enter')searchCity()}}const ps=$('poiSearch');if(ps){ps.onclick=searchPoi;$('poiQuery').onkeydown=e=>{if(e.key==='Enter')searchPoi()};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('poiQuery').value=b.dataset.q;searchPoi()})}}
async function nominatim(q,extra={}){const p=new URLSearchParams({format:'jsonv2',addressdetails:'1',limit:'8',q,...extra});const r=await fetch('https://nominatim.openstreetmap.org/search?'+p,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();return r.json()}
async function searchCity(){const q=$('cityQuery').value.trim();if(q.length<2)return;$('cityResults').innerHTML='<div class="note">Ricerca…</div>';try{const data=await nominatim(q,{featuretype:'city'});$('cityResults').innerHTML=data.length?'':'<div class="note">Nessuna città trovata.</div>';data.forEach(x=>{const name=x.name||x.display_name.split(',')[0];const b=document.createElement('button');b.className='result';b.innerHTML=`<b>${esc(name)}</b><small>${esc(x.display_name)}</small>`;b.onclick=()=>{active().city={name,display_name:x.display_name,lat:+x.lat,lon:+x.lon,bbox:x.boundingbox||null,country_code:x.address?.country_code||''};saveActive();$('cityBlock').innerHTML=selectedCityHtml(active().city);$('poiBlock').classList.remove('hidden');wireCityPoi();map.setView([+x.lat,+x.lon],13)};$('cityResults').appendChild(b)})}catch{$('cityResults').innerHTML='<div class="note">Ricerca non disponibile. Riprova tra qualche secondo.</div>'}}
async function searchPoi(){const c=active()?.city,q=$('poiQuery').value.trim();if(!c||q.length<2)return;$('poiResults').innerHTML='<div class="note">Ricerca…</div>';try{let data=await nominatim(q+', '+c.name,c.country_code?{countrycodes:c.country_code}:{}) ;if(!data.length)data=await nominatim(q,c.country_code?{countrycodes:c.country_code}:{});$('poiResults').innerHTML=data.length?'':'<div class="note">Nessun risultato. Prova una parte del nome.</div>';data.forEach(x=>{const title=x.name||x.display_name.split(',')[0];const b=document.createElement('button');b.className='result';b.innerHTML=`<b>${esc(title)}</b><small>${esc(x.display_name)}</small>`;b.onclick=()=>{addStop({title,subtitle:'',date:'',place:x.display_name,lat:+x.lat,lon:+x.lon,desc:'',image:''});closeModal()};$('poiResults').appendChild(b)})}catch{$('poiResults').innerHTML='<div class="note">Servizio momentaneamente non disponibile.</div>'}}

$('editStopBtn').onclick=editCurrent;function editCurrent(){const s=stops()[current];if(!s)return;openModal(`<h2>Modifica tappa ${current+1}</h2><div class="field"><label>Titolo</label><input id="eTitle" value="${esc(s.title)}"></div><div class="row"><div class="field"><label>Autore / tema</label><input id="eSub" value="${esc(s.subtitle||'')}"></div><div class="field"><label>Data</label><input id="eDate" value="${esc(s.date||'')}"></div></div><div class="field"><label>Luogo</label><input id="ePlace" value="${esc(s.place||'')}"></div><div class="field"><label>Descrizione</label><textarea id="eDesc">${esc(s.desc||'')}</textarea></div><div class="modalFoot"><button class="btn red" id="deleteStop">Elimina tappa</button><button class="btn" id="cancelEdit">Annulla</button><button class="btn primary" id="saveEdit">Salva</button></div>`);$('cancelEdit').onclick=closeModal;$('saveEdit').onclick=()=>{s.title=$('eTitle').value.trim()||'Tappa';s.subtitle=$('eSub').value.trim();s.date=$('eDate').value.trim();s.place=$('ePlace').value.trim();s.desc=$('eDesc').value.trim();saveActive();closeModal();rebuildMarkers();renderSlide()};$('deleteStop').onclick=()=>{if(confirm('Eliminare questa tappa?')){active().stops.splice(current,1);current=Math.max(0,Math.min(current,stops().length-1));saveActive();closeModal();rebuildMarkers();renderSlide();calculateRoute(true)}}}

$('settingsBtn').onclick=()=>openModal(`<h2>Impostazioni itinerario</h2><div class="field"><label>Titolo</label><input id="pTitle" value="${esc(active().title)}"></div><div class="field"><label>Descrizione</label><input id="pDesc" value="${esc(active().desc||'')}"></div><div class="note">Gli itinerari vengono salvati nel browser di questo dispositivo. Usa Esporta/Importa per trasferirli su un altro PC o cellulare.</div><div class="modalFoot"><button class="btn" id="importBtn">Importa</button><button class="btn" id="exportBtn">Esporta</button><button class="btn" id="cancelSet">Annulla</button><button class="btn primary" id="saveSet">Salva</button></div>`);
document.addEventListener('click',e=>{if(e.target?.id==='cancelSet')closeModal();if(e.target?.id==='saveSet'){active().title=$('pTitle').value.trim()||active().title;active().desc=$('pDesc').value.trim();saveActive();$('projectName').textContent=active().title;closeModal()}if(e.target?.id==='exportBtn'){const blob=new Blob([JSON.stringify({version:3,project:active()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(active().title||'itinerario').replace(/[^a-z0-9à-ù]+/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(e.target?.id==='importBtn')$('importPicker').click()});
$('importPicker').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());let p=obj.project||obj;if(!p||!Array.isArray(p.stops))throw 0;p={...p,id:uid(),title:(p.title||'Itinerario')+' · importato',created:Date.now(),updated:Date.now()};projects.push(p);saveProjects();closeModal();openProject(p.id,false)}catch{alert('File non valido.')}e.target.value=''};

function clearRoutes(){routeLayers.forEach(x=>x.remove());routeLabels.forEach(x=>x.remove());routeLayers=[];routeLabels=[];segments=[]}
async function calculateRoute(fit){clearRoutes();const ss=stops();if(ss.length<2){updateRouteSummary();return}for(let i=0;i<ss.length-1;i++){const a=ss[i],b=ss[i+1];let seg;try{seg=await pedestrianRoute(a,b)}catch{seg=fallbackRoute(a,b)}segments.push(seg);const line=L.polyline(seg.points,{color:seg.real?'#b42318':'#777',weight:5,opacity:.9,dashArray:seg.real?null:'8 7'}).addTo(map);routeLayers.push(line);const mid=seg.points[Math.floor(seg.points.length/2)]||[(a.lat+b.lat)/2,(a.lon+b.lon)/2];const lab=L.marker(mid,{interactive:false,icon:L.divIcon({className:'routeLabel',html:`${i+1}→${i+2} · ${fmtDist(seg.distance)} · ${fmtTime(seg.time)}`})}).addTo(map);routeLabels.push(lab)}updateRouteSummary();if(fit)fitProject()}
async function pedestrianRoute(a,b){const req={locations:[{lat:a.lat,lon:a.lon},{lat:b.lat,lon:b.lon}],costing:'pedestrian',costing_options:{pedestrian:{walking_speed:5.0}},units:'kilometers',directions_options:{units:'kilometers'}};const url='https://valhalla1.openstreetmap.de/route?json='+encodeURIComponent(JSON.stringify(req));const r=await fetch(url);if(!r.ok)throw new Error();const j=await r.json(),leg=j.trip?.legs?.[0];if(!leg?.shape)throw new Error();return {real:true,points:decodePolyline6(leg.shape),distance:(leg.summary?.length||j.trip.summary?.length||0)*1000,time:leg.summary?.time||j.trip.summary?.time||0}}
function decodePolyline6(str){let index=0,lat=0,lng=0,out=[];while(index<str.length){let b,shift=0,result=0;do{b=str.charCodeAt(index++)-63;result|=(b&0x1f)<<shift;shift+=5}while(b>=0x20);lat+=(result&1)?~(result>>1):(result>>1);shift=0;result=0;do{b=str.charCodeAt(index++)-63;result|=(b&0x1f)<<shift;shift+=5}while(b>=0x20);lng+=(result&1)?~(result>>1):(result>>1);out.push([lat/1e6,lng/1e6])}return out}
function fallbackRoute(a,b){const d=haversine(a.lat,a.lon,b.lat,b.lon);return {real:false,points:[[a.lat,a.lon],[b.lat,b.lon]],distance:d,time:d/5000*3600}}
function haversine(a,b,c,d){const R=6371000,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,A=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))}
function fmtDist(m){return m<1000?Math.round(m)+' m':(m/1000).toFixed(m<10000?1:0).replace('.',',')+' km'}function fmtTime(s){const m=Math.max(1,Math.round(s/60));return m<60?m+' min':Math.floor(m/60)+' h '+(m%60?m%60+' min':'')}
function updateRouteSummary(){const box=$('routeSummary');if(!segments.length){box.classList.add('hidden');return}const totalD=segments.reduce((s,x)=>s+x.distance,0),totalT=segments.reduce((s,x)=>s+x.time,0),idx=Math.max(0,Math.min(current-1,segments.length-1)),seg=segments[idx];box.innerHTML=`<div class="group"><small>TRATTO ${idx+1}→${idx+2}</small><b>${fmtDist(seg.distance)} · ${fmtTime(seg.time)}</b></div><div class="sep"></div><div class="group"><small>TOTALE A PIEDI</small><b>${fmtDist(totalD)} · ${fmtTime(totalT)}</b></div>`;box.classList.remove('hidden')}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderLibrary();
})();
